warnings

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-[ ! -d dep ] && echo "configure must be run from base uinta directory" && return
+[  -d dep ] && echo -e "\e[33mconfigure must be run from base uinta directory" && return
 cd dep
 
 git submodule update --init --recursive --jobs 12
 
 ### GLFW
-[ ! -d glfw ] && >&2 echo "dep/glfw missing" && return
+[ ! -d glfw ] && >&2 echo -e "\e[33mdep/glfw missing" && return
 mkdir glfw/build 2> /dev/null
 cmake -dCMAKE_BUILD_TYPE=RELEASE -B glfw/build -S glfw
 make --directory glfw/build -j 32
@@ -15,17 +15,17 @@ make --directory glfw/build -j 32
 ### GLAD
 if ! command -v glad &> /dev/null
 then
-	# TODO	This seems wrong to expect glad to be on the path.
+	# TODO	This seems wrong to expect glad to be in the path.
 	#       See if building from dep folder would create a glad executable.
 	#       That would also remove the need to run a `sudo` command.
-	echo "`glad` command not found. Install glad by running `cd dep/glad && sudo python setup.py install`, then re-run this configuration."
+	echo -e "\e[33m`glad` command not found. Install glad by running `cd dep/glad && sudo python setup.py install`, then re-run this configuration."
 	return
 fi
 glad --profile core --out-path glad/build --api gles2=3.2 --spec gl --generator c
 
 
 ### Assimp has a unique build, so we follow their script then reset the git state:
-#[ ! -d log4cplus ] && >&2 echo "dep/log4cplus missing" && return
+#[ ! -d log4cplus ] && >&2 echo -e "\e[33mdep/log4cplus missing" && return
 #cd log4cplus
 #git submodule update --init --recursive
 #./configure
@@ -38,3 +38,4 @@ glad --profile core --out-path glad/build --api gles2=3.2 --spec gl --generator 
 cd ..
 
 echo "Configuration successfully completed."
+\e[33m
